package com.v2soft.styxlib.l5.enums;

// Warning! This file is autogenerated.
// Source file ../../../../../../../../../../../codegen/classes.groovy

public class FileMode {
    public static final long Directory = 0x80000000L;
    public static final long AppendOnly = 0x40000000L;
    public static final long ExclusiveUse = 0x20000000L;
    public static final long MountedChannel = 0x10000000L;
    public static final long AuthenticationFile = 0x8000000L;
    public static final long TemporaryFile = 0x4000000L;
    public static final long SymLinkFile = 0x2000000L;
    public static final long LinkFile = 0x1000000L;
    public static final long DeviceFile = 0x800000L;
    public static final long NamedPipeFile = 0x200000L;
    public static final long SocketFile = 0x100000L;
    public static final long ReadOwnerPermission = 0x100L;
    public static final long WriteOwnerPermission = 0x80L;
    public static final long ExecuteOwnerPermission = 0x40L;
    public static final long ReadGroupPermission = 0x20L;
    public static final long WriteGroupPermission = 0x10L;
    public static final long ExecuteGroupPermission = 0x8L;
    public static final long ReadOthersPermission = 0x4L;
    public static final long WriteOthersPermission = 0x2L;
    public static final long ExecuteOthersPermission = 0x1L;
    public static final long PERMISSION_BITMASK = 0x1ffL;
}
