// Warning! This file is autogenerated.
// Source file ../../../../../../../../../../../codegen/classes.kts
package com.v2soft.styxlib.l5.enums;

/**
* File mode types
**/
public class ModeType {
    public static final int OREAD = 0;
    public static final int OWRITE = 1;
    public static final int ORDWR = 2;
    public static final int OEXEC = 3;
    public static final int OTRUNC = 16;
}
