package com.v2soft.styxlib.l5.enums;

// Warning! This file is autogenerated.
// Source file ../../../../../../../../../../../../../Documents/git/ossrepos/V2StyxLib/codegen/classes.groovy

// QID record types, the type of the file (directory, etc.), represented as a bit vector corresponding to the high 8 bits of the file's mode word.
public class QidType {
    public static final int QTDIR = 128; 
    public static final int QTAPPEND = 64; 
    public static final int QTEXCL = 32; 
    public static final int QTMOUNT = 16; 
    public static final int QTAUTH = 8; 
    public static final int QTTMP = 4; 
    public static final int QTSYMLINK = 2; 
    public static final int QTLINK = 1; 
    public static final int QTFILE = 0; 
}
