package com.v2soft.styxlib.l5.enums;

// Warning! This file is autogenerated.
// Source file ../../../../../../../../../../../../../git/V2StyxLib/codegen/classes.groovy

// QID record types
public class QidType {
    public static final int QTDIR = 128; 
    public static final int QTAPPEND = 64; 
    public static final int QTEXCL = 32; 
    public static final int QTMOUNT = 16; 
    public static final int QTAUTH = 8; 
    public static final int QTTMP = 4; 
    public static final int QTSYMLINK = 2; 
    public static final int QTLINK = 1; 
    public static final int QTFILE = 0; 
}
