package com.v2soft.styxlib.l5.structs;

// Warning! This file is autogenerated.
// Source file ../../../../../../../../../../../codegen/classes.groovy

import com.v2soft.styxlib.l5.enums.QidType;

// Styx QID structure
public record QID(
    int type,
    long version,
    long path
) {
    public static final QID EMPTY = new QID(QidType.QTFILE, 0L, 0L);
}
