#pragma once
// Warning! This file is autogenerated.
// Source file ../../../../Documents/git/V2StyxLib/codegen/classes.groovy

#include <cstdint>

namespace styxlib::enums {

    // Constants FileMode
    const int64_t Directory = 2147483648; ;
    const int64_t AppendOnly = 1073741824; ;
    const int64_t ExclusiveUse = 536870912; ;
    const int64_t MountedChannel = 268435456; ;
    const int64_t AuthenticationFile = 134217728; ;
    const int64_t TemporaryFile = 67108864; ;
    const int64_t SymLinkFile = 33554432; ;
    const int64_t LinkFile = 16777216; ;
    const int64_t DeviceFile = 8388608; ;
    const int64_t NamedPipeFile = 2097152; ;
    const int64_t SocketFile = 1048576; ;
    const int64_t ReadOwnerPermission = 256; ;
    const int64_t WriteOwnerPermission = 128; ;
    const int64_t ExecuteOwnerPermission = 64; ;
    const int64_t ReadGroupPermission = 32; ;
    const int64_t WriteGroupPermission = 16; ;
    const int64_t ExecuteGroupPermission = 8; ;
    const int64_t ReadOthersPermission = 4; ;
    const int64_t WriteOthersPermission = 2; ;
    const int64_t ExecuteOthersPermission = 1; ;
    const int64_t PERMISSION_BITMASK = 511; ;
}
