#pragma once
// Warning! This file is autogenerated.
// Source file ../../../../Documents/git/V2StyxLib/codegen/classes.groovy
#include <cstdint>

namespace styxlib::enums {

    // QID record types, the type of the file (directory, etc.), represented as a bit vector corresponding to the high 8 bits of the file's mode word.
    const int32_t QTDIR = 128; ;
    const int32_t QTAPPEND = 64; ;
    const int32_t QTEXCL = 32; ;
    const int32_t QTMOUNT = 16; ;
    const int32_t QTAUTH = 8; ;
    const int32_t QTTMP = 4; ;
    const int32_t QTSYMLINK = 2; ;
    const int32_t QTLINK = 1; ;
    const int32_t QTFILE = 0; ;
}
