package com.v2soft.styxlib.l5.enums;
// Warning! This file is autogenerated.
// Source file ../../../../../../../../../../../../../codegen/classes.groovy

public class FileMode {
    public static final long Directory = 2147483648;
    public static final long AppendOnly = 1073741824;
    public static final long ExclusiveUse = 536870912;
    public static final long MountedChannel = 268435456;
    public static final long AuthenticationFile = 134217728;
    public static final long TemporaryFile = 67108864;
    public static final long SymLinkFile = 33554432;
    public static final long LinkFile = 16777216;
    public static final long DeviceFile = 8388608;
    public static final long NamedPipeFile = 2097152;
    public static final long SocketFile = 1048576;
    public static final long ReadOwnerPermission = 256;
    public static final long WriteOwnerPermission = 128;
    public static final long ExecuteOwnerPermission = 64;
    public static final long ReadGroupPermission = 32;
    public static final long WriteGroupPermission = 16;
    public static final long ExecuteGroupPermission = 8;
    public static final long ReadOthersPermission = 4;
    public static final long WriteOthersPermission = 2;
    public static final long ExecuteOthersPermission = 1;
    public static final long PERMISSION_BITMASK = 511;
}
