package com.v2soft.styxlib.l5.enums;
// Warning! This file is autogenerated.
// Source file ../../../../../../../../../../../../../codegen/classes.groovy

public class MessageType {
    public static final int Unspecified = 0;
    public static final int Tversion = 100;
    public static final int Rversion = 101;
    public static final int Tauth = 102;
    public static final int Rauth = 103;
    public static final int Tattach = 104;
    public static final int Rattach = 105;
    public static final int Rerror = 107;
    public static final int Tflush = 108;
    public static final int Rflush = 109;
    public static final int Twalk = 110;
    public static final int Rwalk = 111;
    public static final int Topen = 112;
    public static final int Ropen = 113;
    public static final int Tcreate = 114;
    public static final int Rcreate = 115;
    public static final int Tread = 116;
    public static final int Rread = 117;
    public static final int Twrite = 118;
    public static final int Rwrite = 119;
    public static final int Tclunk = 120;
    public static final int Rclunk = 121;
    public static final int Tremove = 122;
    public static final int Rremove = 123;
    public static final int Tstat = 124;
    public static final int Rstat = 125;
    public static final int Twstat = 126;
    public static final int Rwstat = 127;
}
