#pragma once

#include "dataL4.h"
#include <cstdint>
// Warning! This file is autogenerated.
// Source file ../../../../../../../codegen/classes.groovy

namespace styxlib::enums {

    // Constants MessageType
    const Type Unspecified = 0;
    const Type Tversion = 100;
    const Type Rversion = 101;
    const Type Tauth = 102;
    const Type Rauth = 103;
    const Type Tattach = 104;
    const Type Rattach = 105;
    const Type Rerror = 107;
    const Type Tflush = 108;
    const Type Rflush = 109;
    const Type Twalk = 110;
    const Type Rwalk = 111;
    const Type Topen = 112;
    const Type Ropen = 113;
    const Type Tcreate = 114;
    const Type Rcreate = 115;
    const Type Tread = 116;
    const Type Rread = 117;
    const Type Twrite = 118;
    const Type Rwrite = 119;
    const Type Tclunk = 120;
    const Type Rclunk = 121;
    const Type Tremove = 122;
    const Type Rremove = 123;
    const Type Tstat = 124;
    const Type Rstat = 125;
    const Type Twstat = 126;
    const Type Rwstat = 127;
}
