#pragma once
// Warning! This file is autogenerated.
// Source file ../../../../../../../codegen/classes.groovy

namespace styxlib::enums {

    // Constants MessageType
    const int32_t Unspecified = 0;
    const int32_t Tversion = 100;
    const int32_t Rversion = 101;
    const int32_t Tauth = 102;
    const int32_t Rauth = 103;
    const int32_t Tattach = 104;
    const int32_t Rattach = 105;
    const int32_t Rerror = 107;
    const int32_t Tflush = 108;
    const int32_t Rflush = 109;
    const int32_t Twalk = 110;
    const int32_t Rwalk = 111;
    const int32_t Topen = 112;
    const int32_t Ropen = 113;
    const int32_t Tcreate = 114;
    const int32_t Rcreate = 115;
    const int32_t Tread = 116;
    const int32_t Rread = 117;
    const int32_t Twrite = 118;
    const int32_t Rwrite = 119;
    const int32_t Tclunk = 120;
    const int32_t Rclunk = 121;
    const int32_t Tremove = 122;
    const int32_t Rremove = 123;
    const int32_t Tstat = 124;
    const int32_t Rstat = 125;
    const int32_t Twstat = 126;
    const int32_t Rwstat = 127;
}

#include "<cstdint>"