#pragma once
// Warning! This file is autogenerated.
// Source file ../../../../../../../codegen/classes.groovy
#include <cstdint>

namespace styxlib::enums {

    // File mode types
    const int32_t OREAD = 0;
    const int32_t OWRITE = 1;
    const int32_t ORDWR = 2;
    const int32_t OEXEC = 3;
    const int32_t OTRUNC = 16;
}

